#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_ups_output_source(info):
    if len(info) > 0:
        return [ ( None, {}) for x in info if saveint(x[1]) > 0 ]

def check_ups_output_source(item, params, info):
    src = saveint(info[0][1])
    return (0, 'OK - Output Source: %s' \
            % {1:'other(1)', 2:'none(2)', 3:'normal(3)',
                4:'bypass(4)', 5:'battery(5)', 6:'booster(6)',
                7:'reducer(7)'}[src])

check_info['ups_eppc_out_source'] = {
  "inventory_function"  : inventory_ups_output_source,
  "check_function"      : check_ups_output_source,
  "service_description" : "UPS Output Source",
  "snmp_info"           : ( ".1.3.6.1.2.1.33.1", [
                            "1.5", # upsIdentName
                            "4.1", # upsOutputFrequency
                          ]),
  "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.935.10.1"),
}
